src/java/Main/au/AccountController.java


package Main.au;
 // imports
import java.security.NoSuchAlgorithmException;
import java.sql.*;
import java.util.*;
import java.util.logging.*;
import javax.enterprise.context.*;
import javax.faces.application.*;
import javax.faces.context.*;
import javax.inject.*;
import javax.naming.*;
import javax.servlet.*;
import javax.servlet.http.*;
import javax.sql.*;
import javax.validation.constraints.*;

/**
 *
 * @author james + ben + labs i guess 
 * mostly taken from the labs
 */

@Named
@RequestScoped
public class AccountController {

    @Size(min = 1)
    @Pattern(regexp = "[a-zA-Z0-9]{5,}")
    private String username;
    @Size(min = 1)
    @Pattern(regexp = "[a-zA-Z0-9]{5,}")
    private String password;

    // logs you in
    // it doesn't check if you are already logged in
    // i did play around but never got it in the end
    public String loginContainer() {
        FacesContext context = FacesContext.getCurrentInstance();
        HttpServletRequest request = (HttpServletRequest) context.getExternalContext().getRequest();

        try {

            request.login(username, password);

            return "zermon?faces-redirect=true";

        } catch (ServletException e) {
            showError("Incorrect username or password (or you may not have properly configured aipRealm)");

            e.printStackTrace();
            return null;
        }

    }
    // logs you out
    public String logoutContainer() throws ServletException {
        FacesContext context = FacesContext.getCurrentInstance();
        HttpServletRequest request = (HttpServletRequest) context.getExternalContext().getRequest();
        request.logout();
        return "login?faces-redirect=true";
    }
    // makes an account
    public String createAccount() throws DataStoreException, NoSuchAlgorithmException {
        new AccountDAO().createUser(username, password);
        return "login?faces-redirect=true";
    }

   

    // error messages
    private void showError(String message) {
        FacesContext context = FacesContext.getCurrentInstance();
        context.addMessage(null, new FacesMessage(message));
    }

    // auto gen set getters
    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

}

src/java/Main/au/PostController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main.au;

/**
 *
 * @author james
 */
import java.sql.*;
import java.util.*;
import java.util.logging.*;
import javax.enterprise.context.*;
import javax.faces.application.*;
import javax.faces.context.*;
import javax.inject.*;
import javax.naming.*;
import javax.servlet.*;
import javax.servlet.http.*;
import javax.sql.*;
import javax.validation.constraints.Size;

@Named
@RequestScoped
public class PostController {
    // validation and strings stuff
    @Size(min = 1, message = "please enter a title, meow")
    private String title;
    @Size(min = 1, message = "please enter some content ")
    private String content;
    // makes alot of things way easier and less intensive instead of doing lookups for each row.....
    private String UserName;
    private int likes;

    // get all the posts for zermon
    public ArrayList<Post> getAllPosts() throws DataStoreException {

        return new PostDAO().findAll();
    }
    // get all the posts for user management page
    public ArrayList<Post> getUserPosts() throws DataStoreException {
        FacesContext context = FacesContext.getCurrentInstance();
        String uname = context.getExternalContext().getUserPrincipal().getName();
        return new PostDAO().findUserPosts(uname);
    }
    // making a post
    public String createPost() throws DataStoreException {
        FacesContext context = FacesContext.getCurrentInstance();
        String uname = context.getExternalContext().getUserPrincipal().getName();
        new PostDAO().newPost(title, content, uname);
        return "zermon?faces-redirect=true";
    }
    // it calls the delete method in the dao 
    //no controller CAN EVER DO ANY DB WORK
    public void deletePost(int postid) throws DataStoreException {
        new PostDAO().deletePost(postid);
    }
    // increment that like 
    // uncapped so users can feel better about themselves :D
    public void likePost(int likeys, int postid) throws DataStoreException {
        ++likeys;
        new PostDAO().likeyPost(likeys, postid);
    }
    // debugging method 
    // if sun is missing it won't call
    // if i didn't put a form 
    // etc if nothing can call this it's a jsf page issue.
    public String meh() {
        System.out.println("this works");
        return null;
    }

//public void editPost(int postid) throws DataStoreException
//{
//    new PostDAO().editPost(title, content, postid);
//}
//   public Post getPost(){
//       return post;
//   }
//   
//   
//   public void loadPost(int index){
//       System.out.println(index + "Posts COntroller  INDEX");
//       post = FakeDatabase.read(index);
//   }
//   public String saveAsNew()
//   {
//       FakeDatabase.create(post);
//       return "zermon?faces-redirect=true";
//   }
//        
//   public String delete()
//   {
//       System.out.println("post controller DELETE ");
//       FakeDatabase.delete(post.getId());
//       return "zermon?faces-redirect=true";
//   }
//   public String update()
//   {
//       FakeDatabase.update(post);
//       return "zermon?faces-redirect=true";
//   }
    // getters and setters
    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getUserName() {
        return UserName;
    }

    public void setUserName(String UserName) {
        this.UserName = UserName;
    }

}

web/edit.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:b="http://bootsfaces.net/ui"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html">
    <h:head>
  <title>Post a lotta stuff</title>
    </h:head>
    <h:body>
        <b:container>
        
        <h1>Make a edit</h1>
        this actually doesn't work couldn't get the post id to send properly and generate the edit page :(
        <h:form>
            <p>
                <label>  title
                    <h:inputText id="title"
                                 value="#{postController.title}"
                                 class="form-control"
                                 validatorMessage="Must have a title"/>
                </label>
                <h:message for="title"/>
            </p>
            <p><label> Content
                    <h:inputText id="content"
                                 value="#{postController.content}"
                                 class="form-control"
                                 validatorMessage="must have some content" />
                </label>
                
            </p>
             <p>
                
                 <h:commandButton value="Save" action="#{postController.editPost(param.index)}" class="btn btn-default"/>
            </p>
            </h:form>
        
        </b:container>
       </h:body>
</html>


web/illegal.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:b="http://bootsfaces.net/ui"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html">
    <h:head>
  <title>Post a lotta stuff</title>
    </h:head>
    <h:body>
        <b:container>
            <h1> you have tried to do something illegal </h1>
            
        
        <h:link outcome="login" class='btn btn-default'> back to login page</h:link>
        </b:container>
    </h:body>
</html>


web/login.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:b="http://bootsfaces.net/ui"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html">
    <h:head>
  <title>Post a lotta stuff</title>
    </h:head>
    <h:body>
        <b:container>
        <h1>Login Form</h1>
        <p>
            Please remember EVERYTHING IS CASE SENSITIVE :)
        </p>
        <h:form>
            <p>
                <label>Username:
                    <h:inputText value="#{accountController.username}" class="form-control" validatorMessage="blank username field :("/>
                </label>
            </p>
            <p>
                <label>Password:
                    <h:inputSecret value="#{accountController.password}" class="form-control" validatorMessage="blank password field "/>
                </label>
            </p>
            <b:alert >
            <h:messages />
            </b:alert>
            <p>
                <h:commandButton value="Log In" action="#{accountController.loginContainer}" class="btn btn-default"/>
                <h:link outcome="newAccount.xhtml" class="btn btn-default"> new account </h:link>
            </p>
        </h:form>
        </b:container>
    </h:body>
</html>


web/newAccount.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:b="http://bootsfaces.net/ui"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html">
    <h:head>
  <title>Post a lotta stuff</title>
    </h:head>
    <h:body>
        <b:container>
        
        <h1>Make a new account</h1>
        <h:form>
            <p>
                <label> username:  
                    <h:inputText id="username"
                                 value="#{accountController.username}"
                                 class="form-control"
                                 validatorMessage="user is either illegal or blank or below 5 characters"/>
                </label>
                <h:message for="title"/>
            </p>
            <p>
                <label> password:
                    <h:inputText id="password"
                                 value="#{accountController.password}"
                                 class="form-control"
                                 validatorMessage="password is either illegal or blank or below 5 characters"/>
                </label>
                <h:message for="tags" class="label label-danger"/>
            </p>
           
            <h:messages class="label label-danger" />
           
             <p>
                 <h:commandButton value="create account" action="#{accountController.createAccount()}" class="btn btn-default"/>
            </p>
        
        </h:form>
        </b:container>
    </h:body>
</html>




web/newpost.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:b="http://bootsfaces.net/ui"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html">
    <h:head>
  <title>Post a lotta stuff</title>
    </h:head>
    <h:body>
        <b:container>
        
        <h1>Make a new post</h1>
        <i>you can say what ever you like</i>
        <h:form>
            <p>
                <label> Post title:
                    <h:inputText id="title"
                                 value="#{postController.title}"
                                 class="form-control"
                                 />
                </label>
                
            </p>
            <p><label> Content
                    <h:inputText id="content"
                                 value="#{postController.content}"
                                 class="form-control"
                                  />
                </label>
                
            </p>
            <b:alert >
            <h:messages />
            </b:alert>
             <p>
                
                 <h:commandButton value="Save" action="#{postController.createPost()}" class="btn btn-default"/>
            </p>
        </h:form>
        </b:container>
    </h:body>
</html>


web/postmanagement.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:b="http://bootsfaces.net/ui"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html">
    <h:head>
  <title>Post a lotta stuff</title>
    </h:head>
    <h:body>
        <b:container>
            <h1> manage all your posts </h1>
        <h:form>
            <h:dataTable var="row"  value="#{postController.userPosts}" class="table">
            <h:column>
                <f:facet name="header">
                  title
                </f:facet>
                <h:outputText value="#{row.title}"/>
            </h:column>
            <h:column>
                <f:facet name="header">
                     content 
                </f:facet>
                <h:outputText value="#{row.content}" /> 
            </h:column>
            <h:column>
                <f:facet name="header">
                  Modify/delete
                </f:facet>
                <h:link value="Edit" outcome="edit" class="btn btn-default">
                    <f:param name="index" value="#{row.id}"/>
                </h:link>
                 - <h:commandButton value="delete post" action="#{postController.deletePost(row.id)}" class="btn btn-default"/>
            </h:column>
        </h:dataTable>
        </h:form>
            <h:link value="Back to main" outcome="zermon" />
        </b:container>
    </h:body>
</html>


web/zermon.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:b="http://bootsfaces.net/ui"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
    <h:head>
  <title>Post a lotta stuff</title>
    </h:head>
    <h:body>
        <b:container >
            <b:navBar>
         <h:form>

               
              <h:link outcome="newpost.xhtml" class="btn btn-default"> new post  </h:link>
              <h:link outcome="postmanagement.xhtml" class="btn btn-default"> Manage your posts  </h:link>
              <h:commandButton value="Log out" action="#{accountController.logoutContainer}" class="btn btn-default"/>
             </h:form></b:navBar>
            <h1> Main page </h1>
            <i>these are just peoples thoughts in text</i>
            <h:form>
            <ui:repeat var="row" value="#{postController.allPosts}" >
                <b:panel title="#{row.title}" >
                    
                   
                    "<h:outputText value="#{row.content}"/>" -  <i><h:outputText value="#{row.userName}" /></i>   
                    <p></p>     <i class="glyphicon glyphicon-heart"></i> <h:outputText value="#{row.likes}" /> - <h:commandButton value="Like post" action="#{postController.likePost(row.likes,row.id)}" class="btn btn-default"/>
                <p></p>
                </b:panel>
            </ui:repeat>
      
            </h:form>
        
        </b:container>
    </h:body>
</html>